name: Test bundle
on: [push]
jobs:
  test-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- uses: mxschmitt/action-tmate@v3
      - run: sudo snap install juju --classic
      - run: sudo snap install juju-wait --classic
      - run: sudo juju bootstrap localhost --config test-mode=true --config automatically-retry-hooks=false
      - run: sudo juju deploy ./bundle.yaml
      - run: sudo /snap/bin/juju-wait -wv
      - run: sudo juju status

